-- Deprecated: do not apply this legacy schema.
-- Use supabase/migrations/ in filename order; see docs/PRODUCTION_LAUNCH_CHECKLIST.md.
-- The former demo article seed is intentionally retired; published content lives in lib/db/data.js.
